name: SLUS_004.25
sha1: 1dac75ee3a0ef5a62e025a85183076fa1a6cf824
options:
  basename: slus_004.25
  target_path: iso/us/SLUS_004.25
  elf_path: build/slus_004.25.elf
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm
  src_path: src
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/slus_004.25.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80077464
  # ld_gp_expression: main_SCOMMON_START + 0x7FF0

  o_as_suffix: True
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - symbols/slus_004.25.txt

  undefined_funcs_auto_path: undefined_funcs_auto.txt
  undefined_syms_auto_path: undefined_syms_auto.txt


  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Uncomment this line if you need to use the maspsx reorder workaround hack
  # https://github.com/mkst/maspsx?tab=readme-ov-file#include_asm-reordering-workaround-hack
  # include_asm_macro_style: maspsx_hack
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, asm, 800] # estimated
      - [0x58B78, data, 58B78] # estimated
  - [0x68000]
